version: "3.2"

services:
  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin:2.15.0
    container_name: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411

  java-basic-frontend:
    build: ../java-basic-frontend
    container_name: java-basic-frontend
    environment:
      - spring.application.name=Java basic frontend
      - server.port=8081
      - logging.level.fr=DEBUG
      - spring.zipkin.baseUrl=http://zipkin:9411
    ports:
      - "8081:8081"
    depends_on:
      - zipkin

  java-httpclient-frontend:
    build: ../java-httpclient-frontend
    container_name: java-httpclient-frontend
    environment:
      - spring.application.name=Java HttpClient frontend
      - server.port=8080
      - logging.level.fr=DEBUG
      - spring.zipkin.baseUrl=http://zipkin:9411
      - demo.backendBaseUrl=http://java-basic-frontend:8081
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
