version: "3.2"

services:
  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin:2.15.0
    container_name: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0-1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.3.0-1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  java-kafkatemplate-frontend:
    build: ../java-kafkatemplate-frontend
    container_name: java-kafkatemplate-frontend
    environment:
      - spring.application.name=Java KafkaTemplate frontend
      - server.port=8080
      - logging.level.fr=DEBUG
      - spring.zipkin.baseUrl=http://zipkin:9411
      - spring.kafka.bootstrap-servers=kafka:29092
      - demo.kafkaTopic=topicBackend
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
      - kafka

  java-kafkatemplate-consumer:
    build: ../java-kafkatemplate-consumer
    container_name: java-kafkatemplate-consumer
    environment:
      - spring.application.name=Java KafkaTemplate consumer
      - logging.level.fr=DEBUG
      - spring.zipkin.baseUrl=http://zipkin:9411
      - spring.kafka.bootstrap-servers=kafka:29092
      - spring.kafka.consumer.group-id=backend
      - demo.kafkaTopic=topicBackend
    depends_on:
      - zipkin
      - kafka
