version: "3.2"

services:
  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin:2.15.0
    container_name: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411

  mysql:
    image: mysql:8.0.17
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: zipkin-db-demo
      MYSQL_USER: zipkin-db-demo-user
      MYSQL_PASSWORD: zipkin-db-demo-password
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    links:
      - mysql:db
    ports:
      - 8081:8080
    depends_on:
      - mysql

  java-mysql-frontend:
    build: ../java-mysql-frontend
    container_name: java-mysql-frontend
    environment:
      - spring.application.name=Java mysql frontend
      - server.port=8080
      - logging.level.fr=DEBUG
      - spring.zipkin.baseUrl=http://zipkin:9411
      #- spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      #- spring.datasource.url=jdbc:mysql://mysql:3306/zipkin-db-demo
      - spring.datasource.driver-class-name=com.p6spy.engine.spy.P6SpyDriver
      - spring.datasource.url=jdbc:p6spy:mysql://p-nan-roseau:3306/zipkin-db-demo?zipkinServiceName=mySuperDatabase
      - spring.datasource.username=zipkin-db-demo-user
      - spring.datasource.password=zipkin-db-demo-password
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
    ports:
      - 8080:8080
    depends_on:
      - zipkin
      - mysql
