version: "3.2"

services:
  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin:2.15.0
    container_name: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0-1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.3.0-1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  nodejs-kafkajs-frontend:
    build: ../nodejs-kafkajs-frontend
    container_name: nodejs-kafkajs-frontend
    environment:
      - SERVICE_NAME=NodeJS KafkaJS frontend
      - SERVER_PORT=9000
      - DEBUG=true
      - ZIPKIN_BASE_URL=http://zipkin:9411
      - KAFKA_TOPIC=topicBackend
      - KAFKA_CLIENTID=my-producer
      - KAFKA_BROKER_URL=kafka:29092
      - KAFKA_REMOTE_SERVICE_NAME=kafka
    ports:
      - "9000:9000"
    depends_on:
      - zipkin

  nodejs-kafkajs-consumer:
    build: ../nodejs-kafkajs-consumer
    container_name: nodejs-kafkajs-consumer
    environment:
      - SERVICE_NAME=NodeJS KafkaJS consumer
      - DEBUG=true
      - ZIPKIN_BASE_URL=http://zipkin:9411
      - KAFKA_TOPIC=topicBackend
      - KAFKA_CLIENTID=my-consumer
      - KAFKA_BROKER_URL=kafka:29092
      - KAFKA_REMOTE_SERVICE_NAME=kafka
      - KAFKA_CONSUMER_GROUP_ID=my-nodejs-consumer-group
    depends_on:
      - zipkin
      - kafka
